"""Validate and render database-owned content-plan snapshots."""

from __future__ import annotations

from typing import Any


CONTENT_PLAN_SCHEMA = "orin.content-plan-snapshot/v1"


class ContentPlanSnapshotError(ValueError):
    """Raised when a worker receives an invalid content-plan snapshot."""


def validate_content_plan_snapshot(
    snapshot: dict[str, Any], *, client_id: str
) -> list[dict[str, Any]]:
    if snapshot.get("schema") != CONTENT_PLAN_SCHEMA:
        raise ContentPlanSnapshotError("content-plan snapshot has an unsupported schema")
    if snapshot.get("client_id") != client_id:
        raise ContentPlanSnapshotError("content-plan snapshot belongs to another client")
    items = snapshot.get("items")
    if not isinstance(items, list):
        raise ContentPlanSnapshotError("content-plan snapshot items must be an array")

    seen: set[int] = set()
    normalized: list[dict[str, Any]] = []
    for raw in items:
        if not isinstance(raw, dict):
            raise ContentPlanSnapshotError("content-plan item must be an object")
        number = raw.get("item_number")
        if isinstance(number, bool) or not isinstance(number, int) or number < 1:
            raise ContentPlanSnapshotError("content-plan item number must be positive")
        if number in seen:
            raise ContentPlanSnapshotError("content-plan item numbers must be unique")
        seen.add(number)
        status = raw.get("status")
        topic = raw.get("topic")
        target_date = raw.get("target_date")
        if not isinstance(status, str) or not status:
            raise ContentPlanSnapshotError("content-plan item status is required")
        if status == "planned" and (not isinstance(topic, str) or not topic.strip()):
            raise ContentPlanSnapshotError("planned content requires a topic")
        if target_date is not None and not isinstance(target_date, str):
            raise ContentPlanSnapshotError("content-plan target date must be text")
        normalized.append(dict(raw))

    normalized.sort(key=lambda item: item["item_number"])
    selected_number = snapshot.get("selected_item_number")
    if selected_number is not None:
        if isinstance(selected_number, bool) or not isinstance(selected_number, int):
            raise ContentPlanSnapshotError("selected content item number is invalid")
        if selected_number not in seen:
            raise ContentPlanSnapshotError("selected content item is absent from snapshot")
    return normalized


def render_content_plan_markdown(snapshot: dict[str, Any], *, client_id: str) -> str:
    """Render the compatibility projection consumed by the proven pipeline."""
    items = validate_content_plan_snapshot(snapshot, client_id=client_id)
    lines = [
        "# ORIN content queue projection",
        "",
        "Generated from the authoritative database content plan.",
        "Do not edit this file; it is private run evidence, not transaction state.",
        "",
    ]
    for item in items:
        lines.extend(
            [
                f"## Job {item['item_number']}",
                f"Date target: {item.get('target_date') or ''}",
                f"Cluster: {item.get('cluster') or ''}",
                f"Decision: {item.get('decision') or ''}",
                f"Status: {item['status']}",
                f"Topic: {item.get('topic') or ''}",
                f"Target keyword: {item.get('target_keyword') or ''}",
                f"File: {item.get('draft_path') or ''}",
                "Notes:",
            ]
        )
        notes = item.get("notes")
        if isinstance(notes, str) and notes.strip():
            lines.extend(notes.strip().splitlines())
        if item.get("shopify_article_id"):
            lines.append(f"- Shopify Article ID: {item['shopify_article_id']}")
        if item.get("shopify_handle"):
            lines.append(f"- Shopify Handle: {item['shopify_handle']}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"
