export const dashboardData = {
  client: {
    id: "hoverboard_store",
    name: "Hoverboard Store",
    shortName: "HS",
    plan: "Pilot workspace",
  },
  nextArticle: {
    id: 33,
    contentItemId: "33333333-3333-4333-8333-333333333333",
    version: 1,
    title: "Electric Scooter Safety Gear for Children: A Parent’s Checklist",
    keyword: "electric scooter safety gear for kids",
    intent: "Commercial guide",
    status: "Ready for review",
    dueLabel: "Ready now",
    wordCount: 1248,
    readingTime: "6 min read",
    qualityScore: 92,
    checks: [
      "Safety language checked",
      "No unsupported speed claims",
      "Internal links included",
    ],
  },
  operations: {
    scheduler: "Healthy",
    worker: "Online",
    shopifyWrites: "Approval only",
    approvedDraftWritesEnabled: true,
    lastChecked: "Checked moments ago",
  },
  counts: {
    planned: 30,
    drafting: 2,
    review: 3,
    approved: 5,
  },
  recentContent: [
    {
      id: 32,
      title: "Electric Scooter Handlebar Height for Children: Fit Guide",
      stage: "Shopify draft",
      updated: "Today, 20:01",
      owner: "ORIN",
    },
    {
      id: 31,
      title: "Kids Electric Scooter Buying Checklist for Parents",
      stage: "Shopify draft",
      updated: "Today, 11:03",
      owner: "ORIN",
    },
    {
      id: 30,
      title: "Hoverboard Bundle Buying Guide: What Parents Should Compare",
      stage: "Approved",
      updated: "30 Jul, 19:42",
      owner: "You",
    },
  ],
  queue: [
    {
      id: 33,
      contentItemId: "33333333-3333-4333-8333-333333333333",
      version: 1,
      title: "Electric Scooter Safety Gear for Children: A Parent’s Checklist",
      keyword: "electric scooter safety gear for kids",
      stage: "Review",
      status: "Needs you",
      priority: "High",
      due: "Ready now",
    },
    {
      id: 34,
      title: "Hoverboard Battery Care: Charging and Storage Guide",
      keyword: "hoverboard battery care",
      stage: "Drafting",
      status: "Writing",
      priority: "Normal",
      due: "Today",
    },
    {
      id: 35,
      title: "Electric Scooter Tyre Pressure and Everyday Maintenance",
      keyword: "electric scooter tyre pressure",
      stage: "Planned",
      status: "Queued",
      priority: "Normal",
      due: "Tomorrow",
    },
    {
      id: 36,
      title: "Hoverboard Size Guide for Younger and Older Riders",
      keyword: "hoverboard size guide",
      stage: "Planned",
      status: "Queued",
      priority: "Normal",
      due: "4 Aug",
    },
    {
      id: 37,
      title: "Where Can Children Ride Electric Scooters Safely?",
      keyword: "where can kids ride electric scooters",
      stage: "Research",
      status: "Researching",
      priority: "Normal",
      due: "5 Aug",
    },
  ],
  activity: [
    { time: "20:01", label: "Job 32 created as an unpublished Shopify draft" },
    { time: "19:58", label: "Content quality checks passed for Job 32" },
    { time: "11:03", label: "Scheduled dry-run completed with zero Shopify writes" },
    { time: "10:59", label: "Watchdog confirmed the production schedule" },
  ],
  article: {
    id: 33,
    contentItemId: "33333333-3333-4333-8333-333333333333",
    version: 1,
    title: "Electric Scooter Safety Gear for Children: A Parent’s Checklist",
    dek: "A calm, practical guide to choosing everyday protection for young riders, with fit checks parents can repeat before every journey.",
    keyword: "electric scooter safety gear for kids",
    metaTitle: "Electric Scooter Safety Gear for Kids | Parent Checklist",
    metaDescription: "Use this parent-friendly checklist to choose and fit children’s electric scooter safety gear, from helmets to visibility essentials.",
    sections: [
      {
        heading: "Start with the riding environment",
        paragraphs: [
          "The right protective setup starts with where a child will ride, their experience, and the manufacturer’s guidance for the scooter. A quiet, supervised practice area calls for the same careful fit checks as a familiar route.",
          "Before adding any accessory, check that it does not affect steering, braking, visibility, or the rider’s ability to step off safely.",
        ],
      },
      {
        heading: "A helmet that stays in position",
        paragraphs: [
          "Choose a helmet intended for the activity and follow the maker’s sizing instructions. It should sit level, feel secure without pressure points, and remain in place when the rider gently moves their head.",
          "Replace equipment after a significant impact or whenever the manufacturer advises. Damage is not always obvious from the outside.",
        ],
      },
      {
        heading: "Add protection without restricting movement",
        paragraphs: [
          "Wrist, elbow, and knee protection should be snug, correctly oriented, and comfortable through a full range of movement. Loose straps and oversized pads can create new distractions.",
        ],
      },
      {
        heading: "The 60-second pre-ride check",
        bullets: [
          "Helmet level, secure, and comfortable",
          "Pads fastened with no loose straps",
          "Bright clothing and clear visibility",
          "Shoelaces, cuffs, and bags away from moving parts",
          "Scooter checked according to its manual",
        ],
      },
    ],
    evidence: [
      "Draft created from the approved HBStore content plan",
      "Automated checks passed: structure, duplication, safety phrasing",
      "Shopify action is blocked until explicit approval",
      "This prototype records decisions locally only",
    ],
  },
};
